### ISSUE TITLE
Issues in some vectors

### ISSUE THREAD

**Issue by nawaf11** [mustafa0x/qpc-fonts#14]
This table contains some issues of vectors:
![WhatsApp Image 1445-12-19 at 02 41 42](https://github.com/mustafa0x/qpc-fonts/assets/17469798/ef6ca823-a4d0-49f0-b89a-50001e17d938)

The following image show on of the examples, in surah 5, ayah 12 in word(وَءَامَنتُم) .. the issue is (اختفاء  الهمزة) in font file (QCF4_Hafs_09.ttf):
<img width="598" alt="Screenshot 1445-12-19 at 2 47 17 AM" src="https://github.com/mustafa0x/qpc-fonts/assets/17469798/a69a824a-395d-440b-8a41-f5986bbf905d">

**Comment by mustafa0x** [comment]
Extract the fonts from the following file (either by installing first, or extracting the msi directly), and see if they are fixed. If not, we will tell the QPC.

https://nashr.qurancomplex.gov.sa/download/Mushaf%20Publisher%20Win%20Setup%20V3.15.zip

**Comment by mustafa0x** [comment]
resolved
