### ISSUE TITLE
Issues in Hafs V4 vector

### ISSUE THREAD

**Issue by nawaf11** [mustafa0x/qpc-fonts#15]
In Surah Tahaa (20), Ayah (73) there's issues in spaces as shown in the image below (word: ءامنا)

![rn_image_picker_lib_temp_6212d20b-6510-468c-bd7b-162bac5c9949](https://github.com/user-attachments/assets/5c11aff4-73f9-471b-bb55-2c76af427a6c)

The word exists in font file (QCF4_Hafs_25_W)

<img width="727" alt="Screenshot 1446-01-11 at 8 10 00 PM" src="https://github.com/user-attachments/assets/8aee80f3-3124-408f-94d9-9df6140e99ba">

Can you fix it please or report it to the one who can,
جزاكم الله خيرا

**Comment by mustafa0x** [comment]
Please verify the issue exists in desktop program. Then send screenshot to QPC.

https://nashr.qurancomplex.gov.sa/contact/

وجزاكم
