### ISSUE TITLE
AssalamuAlaikum How can I display the name of a Surah in this box? What is the Unicode or glyph code for it? 

### ISSUE THREAD

**Issue by fsfaysalcse** [mustafa0x/qpc-fonts#7]
[
![image](https://user-images.githubusercontent.com/24895913/214623002-6a5a3160-8a26-4e77-bf95-8154558ce488.png)
](url)

**Comment by mustafa0x** [comment]
It's not possible; it must be done manually. I personally haven't ever done it.
